name: CI Linux

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ci-build-test-cpp-linux-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_and_ctest:
    name: Build and Test (linux, ASSERTIONS)
    runs-on: ubuntu-20.04
    env:
      CACHE_DIR: ${{ github.workspace }}/.container-cache
      # either the PR number or `branch-N` where N always increments
      CACHE_KEY: linux-build-test-cpp-asserts-manylinux-v2-${{ format('{0}-{1}', github.ref_name, github.run_number) }}
      ASAN_OPTIONS: detect_leaks=0,detect_odr_violation=1
      LIT_USE_INTERNAL_SHELL: 0
    steps:
      - name: Set unified TZ
        uses: szenius/set-timezone@v2.0
        with:
          # this is an arbitrary choice
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
            
      - name: Free disk space
        uses: descriptinc/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false # This frees space on the wrong partition.
          
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
          ninja: true
          ccache: false
          
      - name: Get ccache 4.9
        run: |
          wget --quiet https://github.com/ccache/ccache/releases/download/v4.9/ccache-4.9-linux-x86_64.tar.xz
          tar -xf ccache-4.9-linux-x86_64.tar.xz
          pushd ccache-4.9-linux-x86_64 && sudo make install && popd
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python deps
        run: |
          pip install "numpy<2" pyyaml "pybind11[global]==2.10.3" lit ml_dtypes

      - name: Enable cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key:  ${{ env.CACHE_KEY }}
          restore-keys: linux-build-test-cpp-

      - name: Hack/patch llvm
        run: |
          git apply \
            --ignore-space-change \
            --ignore-whitespace \
            --verbose \
            --directory \
            llvm-project llvm-libmlir-c-link-libmlir.patch

      - name: Build LLVM
        run: |
          export cache_dir="${{ env.CACHE_DIR }}"
          bash build_llvm.sh
          echo llvm_install_dir="$PWD/llvm-install" >> $GITHUB_ENV
          tar cf llvm-dist-linux.tar llvm-install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: linux_x86_64_llvm_packages
          path: llvm-dist-linux.tar
          if-no-files-found: warn

      - name: Build package
        run: |
          bash build_test_standalone.sh
          
      - name: Double check dylibs and static archives
        run: |
          echo "ldd standalone-opt:"
          ldd standalone-build/bin/standalone-opt
          echo "ldd standalone-opt-capi-test:"
          ldd standalone-build/bin/standalone-capi-test
          echo "ldd standalone-translate:"
          ldd standalone-build/bin/standalone-translate

          echo "find:"
          for so in $(find standalone-build -name *.so); do 
            echo "ldd $so:"
            ldd $so; 
          done

          echo "nm:"
          for so in $(find standalone-build -name *.so); do 
            echo "nm $so:"
            nm -gDC $so; 
          done

      - name: Save cache
        if: ${{ !cancelled() }}
        uses: actions/cache/save@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ env.CACHE_KEY }}

      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3.18
      #   with:
      #     limit-access-to-actor: true
      #     install-dependencies: true
